lane_detection_node: 
  ros__parameters: 
    Hue_low : 13 
    Hue_high : 37 
    Saturation_low : 88 
    Saturation_high : 227 
    Value_low : 80 
    Value_high : 239 
    number_of_lines : 4 
    error_threshold : 0.08 
    Width_min : 4 
    Width_max : 236 
    gray_lower : 14 
    inverted_filter : 0 
    kernal_size : 8 
    erosion_itterations : 1 
    dilation_itterations : 1 
    crop_width_decimal : 1.0 
    rows_to_watch_decimal : 0.77 
    rows_offset_decimal : 0.37 
    camera_centerline : 0.35 
calibration_node: 
  ros__parameters: 
    Hue_low : 13 
    Hue_high : 37 
    Saturation_low : 88 
    Saturation_high : 227 
    Value_low : 80 
    Value_high : 239 
    number_of_lines : 4 
    error_threshold : 0.08 
    Width_min : 4 
    Width_max : 236 
    gray_lower : 14 
    inverted_filter : 0 
    kernal_size : 8 
    erosion_itterations : 1 
    dilation_itterations : 1 
    crop_width_decimal : 1.0 
    rows_to_watch_decimal : 0.77 
    rows_offset_decimal : 0.37 
    camera_centerline : 0.35 
lane_guidance_node: 
  ros__parameters: 
    Kp_steering : 0.7 
    Ki_steering : 0.0 
    Kd_steering : 5e-06 
    zero_throttle  : 0.0 
    max_throttle : 0.8
    min_throttle : 0.7
    error_threshold : 0.08 
    max_right_steering : 1.0 
    max_left_steering : -1.0 
vesc_twist_node: 
  ros__parameters: 
    max_rpm : 20000 
    steering_polarity : 1 
    throttle_polarity : 1 
    zero_throttle  : 0.0 
    max_throttle : 0.8 
    min_throttle : 0.7
    max_right_steering : 1.0 
    straight_steering : 0.0 
    max_left_steering : -1.0 
adafruit_twist_node: 
  ros__parameters: 
    steering_polarity : 1 
    throttle_polarity : 1 
    zero_throttle  : 0.0 
    max_throttle : 0.2 
    min_throttle : 0.1 
    max_right_steering : 1.0 
    straight_steering : 0.0 
    max_left_steering : -1.0 
